### ISSUE TITLE
cannot develop or build

### ISSUE THREAD

**Issue by dansha** [jaxx2104/gatsby-starter-bootstrap#1]
when i gatsby develop 
I get:
 Cannot find module 'core-js/library/fn/symbol/iterator'
 @ (webpack)-require/lib/webpackRequireEntrypoint.js 1:20-41

I think it is babel related 

any ideas?

**Comment by jaxx2104** [comment]
I try to it, but it doesn't reproduce.
Please you try again.

```
$ gatsby new gatstrap https://github.com/jaxx2104/gatsby-starter-bootstrap
$ cd gatstrap
$ gatsby develop
```

And could you tell me node.js and npm version.
