### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by wsaborio** [jaxx2104/gatsby-starter-bootstrap#12]
development works great but gatsby build consistently fails with the below error:

Generating CSS
Compiling production bundle.js
Generating static HTML for pages

Error: TypeError: Cannot read property 'jquery' of undefined
    at render-page.js:52224:22
    at Object.<anonymous> (render-page.js:52228:3)
    at Object.<anonymous> (render-page.js:55749:31)
    at __webpack_require__ (render-page.js:30:30)
    at Object.<anonymous> (render-page.js:51165:2)
    at __webpack_require__ (render-page.js:30:30)
    at Object.defineProperty.value (render-page.js:42784:27)
    at __webpack_require__ (render-page.js:30:30)
    at Object.exports.__esModule (render-page.js:81:22)
    at __webpack_require__ (render-page.js:30:30)

Generating static HTML for pages failed
See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

debugging in the public folder's render-page.js shows an error in the following:

	+function ($) {
	  var version = $.fn.jquery.split(' ')[0].split('.')
	  if ((version[0] < 2 && version[1] < 9) || (version[0] == 1 && version[1] == 9 && version[2] < 1) || (version[0] >= 4)) {
	    throw new Error('Bootstrap\'s JavaScript requires at least jQuery v1.9.1 but less than v4.0.0')
	  }
	}(jQuery);

i'm guessing there's an assumption at this point in the build that jquery's been imported but the render-page.js doesn't seem to show that. any ideas where this might be fixed?

**Comment by jaxx2104** [comment]
I can't reproduce the error 🤔
Retry installation.
```sh
$ npm i -g gatsby
$ gatsby -V
1.6.5

$ gatsby new gatstrap https://github.com/jaxx2104/gatsby-starter-bootstrap
$ cd gatstrap/
$ npm run build (or deploy)
```

**Comment by wsaborio** [comment]
i'm on 1.6.6, will roll back and give it another go

**Comment by jaxx2104** [comment]
Fix error 🎉
Try update gatsby-starter-bootstrap.

**Comment by wsaborio** [comment]
good to go!
