### ISSUE TITLE
Font Changing

### ISSUE THREAD

**Issue by kubet** [jaxx2104/gatsby-starter-bootstrap#124]
Lets say i whant to change just h1 on profile page to some other font and i add in scss #h1id {font-family: Merriweather;} and it works in develop and netlify host  but just on my pc (because i have Merriweather installed on my pc) when i try to load ex. mysite.netlify.com it in other pc or my phone font is default system font.
i added it to fonts.scss and did !default but it makes every text that font.
How do i import custom fonts that i have installed on my pc, and to load on other devices?
How do i change font for just one text ex h1?

**Comment by jaxx2104** [comment]
Sorry. consider StackOverflow.

**Comment by jaxx2104** [comment]
![LGTM](https://pbs.twimg.com/media/Dudu-TMU8AA9jX4?format=jpg)
