### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by jonnysmillie** [jaxx2104/gatsby-starter-bootstrap#162]
Hi, love this starter and I'm trying to use it as the base for a new starter but I'm finding it difficult to implement pagination on blog posts without totally rewriting the way pages and posts are created. It would be extremely useful to see pagination implemented on this starter if anyone is able to do so?

**Comment by jaxx2104** [comment]
Pagination component is difficult to support.
unnecessary because the image is load when scrolling with gatsby-remark-images.

Of course you can customize and implement pagination 👍

**Comment by bpmottathai** [comment]
What is the role of gatsby-remark-images in pagination. I think the OP is asking about pagination in the blog index page. Will it have auto scroll effect with gatsby-remark-images?
