### ISSUE TITLE
Javascript not working

### ISSUE THREAD

**Issue by mfernandez314** [jaxx2104/gatsby-starter-bootstrap#2]
I tried to add a bootstrap dropdown on the navbar with clean repository but it doesnt works, any idea?

**Comment by BSchneppe** [comment]
i have exactly the same issue

**Comment by jaxx2104** [comment]
Gatsrap did not load bootstrap.js, so navbar components did not work.
I fixed it with commit 46ca8d398f6d24ce9615ba95673a143f61a8fcca.
