### ISSUE TITLE
about forced reflow

### ISSUE THREAD

**Issue by FourEyebrowXiake** [jaxx2104/gatsby-starter-bootstrap#20]
![image](https://user-images.githubusercontent.com/18180417/31013673-bf36ad5c-a549-11e7-9ae3-cac037fe152e.png)

When I tested the home page performance, I saw this scene. I do not know what's going on.

Do you know why?

**Comment by jaxx2104** [comment]
What did not you understand? 
Please tell me more details.

**Comment by FourEyebrowXiake** [comment]
Why a forced reflow occurs？
![image](https://user-images.githubusercontent.com/18180417/31023734-6290b6a8-a56f-11e7-8a3f-7ac9a89f6e44.png)
![image](https://user-images.githubusercontent.com/18180417/31023764-79c005fe-a56f-11e7-9c79-46331c49ff5c.png)
Really jQuery wrong?

**Comment by jaxx2104** [comment]
Debugging, `react-lazyload` caused forced reflow.
disable lazyload [pages/index.js#L6](https://github.com/jaxx2104/gatsby-starter-bootstrap/blob/d4329c5159c81f3c4c2d5937efbb208e8961adfc/src/pages/index.js#L6).

**Comment by FourEyebrowXiake** [comment]
how do you find this debug,I would like to know how to find bug？
Can you give me some advice?
Thanks

**Comment by FourEyebrowXiake** [comment]
@jaxx2104

**Comment by FourEyebrowXiake** [comment]
how dose react-lazyload cause the problem

**Comment by jaxx2104** [comment]
First rendering occurs forced reflow.
lazy load requires many dom operations.
