### ISSUE TITLE
/src/layouts/gatstrap.css no found. Expected from your one page guide.

### ISSUE THREAD

**Issue by Kowai** [jaxx2104/gatsby-starter-bootstrap#224]
/src/layouts/gatstrap.css no found.

 Expected from your one page guide.

**Comment by jaxx2104** [comment]
I can't reproduce the error.
Retry installation.
```sh
$ npm i -g gatsby
$ gatsby -V
$ gatsby new gatstrap https://github.com/jaxx2104/gatsby-starter-bootstrap
$ cd gatstrap/
$ gatsby develop
```

**Comment by Kowai** [comment]
Nah sorry I wasn't clear.
In your github page presenting the project, you talk about documents and in the custom section you mentionned a theme in 

/src/layouts/gatstrap.css

But couldn't find it. There is no layout folder.

**Comment by bpmottathai** [comment]
OP is asking about your documentation. Actually it is in /src/scss/getstrap.scss.
Please tell me how to change themes, you reffering to semantic part

**Comment by jaxx2104** [comment]
Thanks 👍 #483
