### ISSUE TITLE
SyntaxError: Unexpected token: name (context)...

### ISSUE THREAD

**Issue by ukozdan** [jaxx2104/gatsby-starter-bootstrap#31]
## Description

Trying to build fresh project as per "Get Started" docs

### Environment

Gatsby version: 1.1.37
Node.js version: 9.4.0
Operating System: Windows 10 Enterprise

### File contents (if changed):

No changes to contents. 

### Actual result

What happened.

`$ gatsby build
success delete html files from previous builds — 0.017 s
success open and validate gatsby-config.js — 0.005 s
success copy gatsby files — 0.047 s
success onPreBootstrap — 0.012 s
success source and transform nodes — 0.116 s
success building schema — 0.372 s
success createLayouts — 0.014 s
success createPages — 0.024 s
success createPagesStatefully — 0.028 s
success onPreExtractQueries — 0.004 s
success update schema — 0.122 s
success extract queries from components — 0.074 s
success run graphql queries — 0.067 s
success write out page data — 0.013 s
success write out redirect data — 0.002 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 4.937 s

success Building CSS — 7.212 s

error Generating JavaScript bundles failed

  Error: component---src-templates-blog-post-js-b29bd044b77c466ea753.js from UglifyJs
  SyntaxError: Unexpected token: name (context) [./~/striptags/src/striptags.js:26,0]`

What should happen?

### Steps to reproduce

1\.

2\.

3\.

...

**Comment by ukozdan** [comment]
I have also registered this error with Gatsby because I don't know what has caused the error.

**Comment by jaxx2104** [comment]
Fixed Issue!
