### ISSUE TITLE
Help understanding how CSS is served

### ISSUE THREAD

**Issue by mikepuglisi** [jaxx2104/gatsby-starter-bootstrap#369]
When I run `yarn build` and look at the .html files generated, the entire bootstrap library is served on every page.

See: 

![image](https://user-images.githubusercontent.com/37956042/56930382-79164d00-6aaa-11e9-80cd-8b8bb8a10c3a.png)

This seems undesirable.

When I view the source of the demo project on Netlify, I don't see any css served in the actual page being served (https://gatstrap.netlify.com/).

Can you explain how the CSS is being served exactly?

SideNote: I installed the gatsby-plugin-purgecss plugin in an attempt to remove some of the css bloat, but now that I see no css in the netlify markup, I'm wondering if that is even needed / advised.

**Comment by anantoghosh** [comment]
@mikepuglisi Gatsby always inlines all the css in the head, so bootstrap is included in every page.
What your are looking at https://gatstrap.netlify.com/ is not the actual source but the file served by the service worker (added by gatsby-plugin-offline).   
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-offline#notes

gatsby-plugin-purgecss will indeed help to decrease the amount of styles inlined.
