### ISSUE TITLE
How does this actually add bootstrap?

### ISSUE THREAD

**Issue by macsj200** [jaxx2104/gatsby-starter-bootstrap#4]
I tried using the boilerplate gatsby template and installing bootstrap via npm, and it didn't seem to load the package. How does this project include bootstrap?

**Comment by jaxx2104** [comment]
Could you show me the code (or cmd)?

Or try the gatsby-starter-bootstrap installation.
`gatsby new gatstrap https://github.com/jaxx2104/gatsby-starter-bootstrap`

**Comment by macsj200** [comment]
Apologies, my initial question was rather unclear.

I'm asking how exactly bootstrap is included **by this boilerplate**. What are the steps you took to bundle and apply bootstrap inside of gatsby?

**Comment by jaxx2104** [comment]
This step 😄 
```
$ gatsby new gatsby-site
$ cd gatsby-site
$ npm install --save bootstrap
```

**Comment by macsj200** [comment]
Did that actually get the bootstrap css and js to bundle with the page, or did you have to explicitly import the css and js somehow?

**Comment by jaxx2104** [comment]
css
https://github.com/jaxx2104/gatsby-starter-bootstrap/blob/fba23abeda73ba84a5c0c4f627cf9f773b595584/static/scss/gatsrap.scss#L94

js
https://github.com/jaxx2104/gatsby-starter-bootstrap/blob/68ab84b9853997832ba0288fd808a3b918d8037c/html.js#L17

**Comment by sidhuko** [comment]
Could the javascript be bundled with webpack? You don't have to include the whole dependency by loading source files directly.

**Comment by jaxx2104** [comment]
I don’t know 😭
If you can the bundled with webpack please PR.

**Comment by Superjisan** [comment]
@jaxx2104 thanks a lot for the reference

**Comment by kaptiin-tuekhov** [comment]
Hey @jaxx2104 found this thread and then noticed you got bundling Bootstrap js to work and then went back to the CDN. Could you advise on what the issues were and whether its even worth an attempt at bundling?

**Comment by exrishu** [comment]
@jaxx2104  I want to import the js bootstrap into to index.js from node_modules. as we import _Link from gatsby-link_ and _React from react_  . I have installed the bootstrap through npm. Is there is anyway to do that?
