### ISSUE TITLE
v2, fontawesome 5 upgrade

### ISSUE THREAD

**Issue by millette** [jaxx2104/gatsby-starter-bootstrap#58]
Hello,

for the v2 branch, do you want a PR to upgrade react-fontawesome to 0.1.0 (and related modules)?

For reference:

<https://github.com/millette/gatsby-starter-location-github/blob/a7d88d0ff0b7870fe0359e09d525c4403a66f63a/src/components/Icon/index.js>

and in package.json:
```
"devDependencies": {
  "@fortawesome/fontawesome-svg-core": "^1.2.0",
  "@fortawesome/free-brands-svg-icons": "^5.1.0",
  "@fortawesome/react-fontawesome": "0.1.0"
}
```

**Comment by jaxx2104** [comment]
Thanks! Fix it #55
