### ISSUE TITLE
Error when you install the repo

### ISSUE THREAD

**Issue by darcelvictor** [jaxx2104/gatsby-starter-bootstrap#612]
Error: Invalid hook call. Hooks can only be called inside of the body of a fun  ction component. This could happen for one of the following reasons:
  1. You might have mismatching versions of React and the renderer (such as Reac  t DOM)
  2. You might be breaking the Rules of Hooks
  3. You might have more than one copy of React in the same app
  See https://fb.me/react-invalid-hook-call for tips about how to debug and fix   this problem.

**Comment by jaxx2104** [comment]
I just did yarn install and it installs just fine.
Can you give me instructions on how to check for errors here as well?
