### ISSUE TITLE
Every scss file is global?

### ISSUE THREAD

**Issue by kubet** [jaxx2104/gatsby-starter-bootstrap#68]
When i make new page or component and make scss file and import it, so if i write style for ex. h1 it is applied to every page,component but i imported it just in page.js or jsx.

**Comment by jaxx2104** [comment]
Please be more specific about it?

**Comment by kubet** [comment]
![image](https://user-images.githubusercontent.com/41026612/43213980-3be75ef8-9038-11e8-89d7-dd55dde0333f.png)
for ex if i put html, body {
    overflow-y: hidden;
}   or img {
    margin: 50px;
} in styles.scss in SiteNavi and imported only in index.jsx in same folder but somehow it my other pages and components have same effect of  img margin 50px or every other page or component now has no scroll effect 'overflow-y: hidden;'

**Comment by kubet** [comment]
It is like every scss file is global

**Comment by jaxx2104** [comment]
It's a specification of loader.
If you want to be local scoped, Try it.
https://www.gatsbyjs.org/tutorial/part-two/#css-modules
